spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

decrypt:
  privateKey: ENC(PB59/n83MIns6fCnZBE1kuOmFXifmX7BKvtmTyj6ObsJNbH9LW+Ij9Sio6oQWDjl88uFln52hDAd4WyiWMiHJ8nJF8ymTbXkyLMcTtLSwpxEjrOSpXZinjbOmwiCq5Z3MYrn6vVG5vVnYum0ViTwcnO+PCK7I2UZGRPuooXWMV92vNH0DpJ0i41cHebJwkGVjPQltAQXc5eFh6E3n4veseyydadWlEni+aF6Z8nLCgHfvUXzb1njIqz2omVkXKOYh9GcWac2RoVxgjKPs3026+gapzddjlaPyaZfg4wuNCmV2C2HXijJXFhuc6ZHYcKBzIVF31SzNW9PUiJUNu0Z6ke7FabNfuk/WiOyAROPgfWU4KR40flDsqadHdFKzKaReagJV2LScZ7jbyFEru3gfgtudfeLunfNVuvPtMZA0hTvQwJlS/Lf0myUOeiw79DerbBKNdog7Ua7Cjk72DYJIc7n3U+c14pLR+UD1rk6Bj+RB/efoemGVM8HRHpDMd7zX1ZMmblcQwqlIhN6a365JHt+/Fcqk7VyUbuLICHcs7CowaaE2CDHHbtRYkeds6o81JdWkHbpf5CZBxICU1jhwIGFB2QoSvSKmxTy/SI0Uivrx29pqnfAHFPtGInWw4dPbu2WBQR4X9duF0CAB7z5R0LUn6wurdGIeczSaLcjygw79L1u5HbSBhSpIHPvpAMlPKhBgdUgOuQflhf0B+EgH35tGGGsBHtyns/mdVhcQJJ3gXFFfH950GSZqWurAVbwi2t6jahfwKlOSq/agKb7ZfC1PBHSKhbscjxyj4P1pvrgqo8Oep5cE2+MZqbKU0F46hhuU1XJJetK9/vVId1omnPYYEO1xkt+QQwbq1AMpO9WHzl26x56n4kgcPGiiEjke0rLjugSWqRzbScgo7yVXN3XiFrcvt09jSxfJ7llkyt6rcSMTtcFBBFRQPtPGbU8F4f/2BtO2UIZqaNzuHa+IEQSjwq81iw1wASWcguQlU8QRnxj75+Gg1aLEyBjujNQMr++/pofMOSp1O9eiNagxPMJJtEHzotNtGRzoWd/DMxngxu6g4VKzZkijD/S8neZ1B9Fu29Iq7hgfRm9Rxr0ECe18CuDsUdLMs/XcJdRcEBEE8YnSW+vMwfpf9y2yU0/zVKgnCdPe5t76VYvzquHeUiILHuZjjZDLhR3yOC8gszKcCBm0z1KXivqRuFwqYXkcjq37LRqE/qwB4h5QREQJA==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  secret: ENC(X1OivZs9x8lcG8TsReO17Mlti/ppHMXQAAN8kkSULplg7J+eD2wLTTQus0q9ezlOJa/sxHKt5o0LqxtIZfR2Ld8AwERyTCgVO65lhB0D49KEIzcUNqyxpjPQGykii/95dib3neIZadxXXRGx6Ak/3w==)
  accessTokenValidationSecond: ENC(9fZ5xUQa88LAz2seX45f9g==)
  refreshTokenValidationSecond: ENC(SPh6huC5tdQWFWLnFuadcg==)
