spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

decrypt:
  privateKey: ENC(K5vdfa7q8kru43xD5U8JXwm9YYKZq6YYXCbp+sRBwudvaMaSfsgw7HoBBcujoAI0AeJSjMMMkbknCSNSEZp/hLOc7ERLfp8U0quIZ9pspsfv+D82stsvM9enza2oxYuIJXLBsyLPvaey5U06KUqWIe6yfH4r3QZYhvAm5dG3Qt2jD8ogAk5o1+575pDwLcMzVa562GMOdg2aZP4b4U2qdDu1415VpNP0THs2N/xM1aThGKb/Utwf/xCdJD3US1BAx97CMRQyXsSWfOffXBTOiP9OpWVZPmnnH0rlFR877l75tQHWKkCv2EqVEJDNxIE9EY9RmvycVFti3YShpY8rmjEe219Wp5qyarsY2SfaEa+lzfyfVd8aiTeT18AO6v0jtKTU+/N4MiNYKlk2SJeBBA/WO51MwS9Ax6e7u49Oeo5mRw5MDmTMXEmIV4rwlMlzFWt1vYunAD8dT28bRt2Lmkb9Lih73gx73A08Tcwt8+YVo+6C6XL9Ym73fCZNkZ25De5BrvMgJM2m3WHCi9iZ38MWK/qglj7EBa/eUZoA+Q5V9TrP6KS6TEgmgR6o2T6byLn+ynhnyvZ5PFslHJ3SbYCPDUpSNQtTgNn1VFx+AUUqjDKHtG4X+JTQfQrjPPceKsBc4ZTeUpXitErJiU0PVBnAVkJdoOCaRAdM7KQ4CyW95FvdewbZtN6uCFJdoZAuVPyTjm/eS55LrrPTnp3m1nuknJHlFQYcyq5NCpv1bc9EqnsOdpKN6XbYvEI3ehgzoog+gcpD9xqURvwAl66wNk5xez82P1UtoDjlcmryOO4tfc+ZvMOXNlfi3s/E+2a5B7KOsWKTvlV3IQ/PjhMVVJ6u9W7CSXvMlrcD3h0nP93cr4BOlVizWtoBDbdU0Dffra2CAJMofmYuOaXW5QvbwA5kFz+p1lOfU8hwOOsBqtYF9TD9JJxvwRKyDtqRbvT6Hd1v0MDae4v6O6NLvLlYfF6R1irv/zpgxZhhIhYjDHzL/SJPK8KYg00TFjGqPjULvMn+DXL9pJ53x8/zXKJrQmIUrtXAFRoBCNpB/o+Go+M5TLbe5xbDZgW3voBVZ1qQDk92tcxPV4wxCwHh8QlANGJKHe9UEDI9CwnHEkstILquF68XAbXI9jLtlHluXMCu)
  test: ENC(AP+Ie1yirqSUARtpQtCLsg==)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
